### ISSUE TITLE
git merge conflicts in forecast.io.js 

### ISSUE THREAD

**Issue by rjbultitude** [iantearle/forecast.io-javascript-api#14]
Hi Ian

It looks like the recent merge of my fork into yours has conflicts. In the main forecast.io.js file there's merge conflict markers on lines 46, 59, 100 and 259 which breaks the script.

**Comment by rjbultitude** [comment]
Further to the above there are merge conflict markers in the index file too. Happy to fix if you want to grant me [full access](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/)

**Comment by iantearle** [comment]
Hi Rich, yeah, sorry - had a nightmare merging in - not even sure, hadn't had time to fix. Thanks for the offer. You should be now set as a collaborator.
